/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Course,
  Student,
  Submission,
  Invoice,
  Coupon,
  Lead,
  Announcement,
  Review,
  PaymentTransaction,
  AuditLog,
  ReferralCode,
  ReferralConversion,
} from './types';

export const initialCourses: Course[] = [
  {
    id: "course_1",
    name: "Free Workshop on Prompt Engineering",
    level: "Free",
    levelClass: "badge-free",
    price: "Free",
    priceNum: 0,
    status: "Published",
    lessonsCount: 4,
    studentsCount: 512,
    hasCertificate: false,
    updatedAt: "02/06/2026",
    thumbnail: "https://images.unsplash.com/photo-1618401471353-b98aedd07871?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "course_2",
    name: "Starter Mini Course in Vibe Coding",
    level: "Starter",
    levelClass: "badge-starter",
    price: "590.000đ",
    priceNum: 590000,
    status: "Published",
    lessonsCount: 8,
    studentsCount: 286,
    hasCertificate: true,
    updatedAt: "02/06/2026",
    thumbnail: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "course_ai_agent_bootcamp",
    name: "AI Agent & Vibe Coding Bootcamp",
    level: "Core",
    levelClass: "badge-core",
    price: "2.990.000đ",
    priceNum: 2990000,
    status: "Published",
    lessonsCount: 24,
    studentsCount: 428,
    hasCertificate: true,
    updatedAt: "01/06/2026",
    thumbnail: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "course_n8n_web_automation",
    name: "Web Automation with n8n",
    level: "Advanced",
    levelClass: "badge-advanced",
    price: "1.290.000đ",
    priceNum: 1290000,
    status: "Published",
    lessonsCount: 18,
    studentsCount: 132,
    hasCertificate: true,
    updatedAt: "01/06/2026",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "course_5",
    name: "Premium Mentoring: Product MVP",
    level: "Premium",
    levelClass: "badge-premium",
    price: "12.000.000đ",
    priceNum: 12000000,
    status: "Draft",
    lessonsCount: 10,
    studentsCount: 4,
    hasCertificate: true,
    updatedAt: "31/05/2026",
    thumbnail: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "course_6",
    name: "B2B Training for Corporations",
    level: "B2B",
    levelClass: "badge-b2b",
    price: "Custom",
    priceNum: 0,
    status: "Archived",
    lessonsCount: 6,
    studentsCount: 120,
    hasCertificate: false,
    updatedAt: "29/05/2026",
    thumbnail: "https://images.unsplash.com/photo-1618401471353-b98aedd07871?auto=format&fit=crop&w=300&q=80",
  }
];

export const initialStudents: Student[] = [
  {
    id: "1",
    name: "Phạm Đức Trí",
    email: "tri@email.com",
    phone: "0987 654 321",
    status: "Active",
    statusClass: "badge-green",
    createdAt: "28/05/2026",
    updatedAt: "02/06/2026 09:15",
    avatar: "PT",
    avatarClass: "avatar-pt",
    needCourse: "AI Agent & Vibe Coding Bootcamp",
    needLevel: "Đã dùng ChatGPT cơ bản",
    needGoal: "Tạo website/app bằng AI",
    needNote: "Muốn học để build sản phẩm cá nhân.",
    courses: [
      { name: "AI Agent & Vibe Coding Bootcamp", status: "Active", statusClass: "badge-green", progress: 45, progressClass: "orange", date: "28/05/2026" },
      { name: "Vibe Coding Basics", status: "Completed", statusClass: "badge-gray", progress: 100, progressClass: "green", date: "15/03/2026" }
    ],
    lessons: "12 / 24 bài học",
    quiz: "8.5 / 10",
    time: "18 giờ 45 phút",
    exercises: "4 / 6 bài tập",
    submissions: [
      { exercise: "Assignment 1: Prompt Engineering basics", date: "30/05/2026", status: "Đã duyệt", statusClass: "badge-green" },
      { exercise: "Assignment 2: Vibe Coding setup", date: "02/06/2026", status: "Đang chấm", statusClass: "badge-orange" }
    ],
    certificates: [
      { name: "Chứng chỉ Vibe Coding Basics", code: "CERT-VIBE-77391", date: "15/03/2026" }
    ],
    notes: "Cần chú ý hỗ trợ thêm phần cấu hình API keys ở bài 3.",
    accountBalance: 750000,
    ledgerTransactions: [
      { id: "TX-998811", type: "Credit (Nạp tiền)", amount: "+1.000.000đ", desc: "Nạp tiền học phí hoàn trả từ đơn MAY-ORD-2026-0004", time: "20/05/2026 10:15" },
      { id: "TX-998812", type: "Debit (Trừ tiền)", amount: "-250.000đ", desc: "Mua tài liệu khóa học AI Automation", time: "22/05/2026 14:30" }
    ]
  },
  {
    id: "2",
    name: "Nguyễn Hoàng Anh",
    email: "anh.nguyen@email.com",
    phone: "0812 345 678",
    status: "Active",
    statusClass: "badge-green",
    createdAt: "26/05/2026",
    updatedAt: "27/05/2026 14:20",
    avatar: "HA",
    avatarClass: "avatar-nh",
    needCourse: "AI Agent & Vibe Coding Bootcamp",
    needLevel: "Mới học Python cơ bản",
    needGoal: "Tự động hóa công việc kinh doanh",
    needNote: "Cần hỗ trợ về phần API integration.",
    courses: [
      { name: "AI Agent & Vibe Coding Bootcamp", status: "Active", statusClass: "badge-green", progress: 72, progressClass: "green", date: "26/05/2026" }
    ],
    lessons: "18 / 24 bài học",
    quiz: "9.2 / 10",
    time: "25 giờ 30 phút",
    exercises: "5 / 6 bài tập",
    submissions: [
      { exercise: "Assignment 2: Automation with n8n", date: "29/05/2026", status: "Đã duyệt", statusClass: "badge-green" }
    ],
    certificates: [],
    notes: "Học nhanh, tự làm được các bài tập tích hợp webhook.",
    accountBalance: 0,
    ledgerTransactions: []
  },
  {
    id: "3",
    name: "Trần Linh",
    email: "linh.tran@email.com",
    phone: "0909 123 456",
    status: "Active",
    statusClass: "badge-green",
    createdAt: "24/05/2026",
    updatedAt: "01/06/2026 10:05",
    avatar: "TL",
    avatarClass: "avatar-tt",
    needCourse: "Vibe Coding Basics",
    needLevel: "Non-tech, chưa có kinh nghiệm",
    needGoal: "Học lập trình cơ bản để giao tiếp với dev",
    needNote: "Học chậm hơn, cần giải thích kỹ lý thuyết.",
    courses: [
      { name: "Vibe Coding Basics", status: "Active", statusClass: "badge-green", progress: 20, progressClass: "orange", date: "24/05/2026" }
    ],
    lessons: "2 / 10 bài học",
    quiz: "7.0 / 10",
    time: "4 giờ 15 phút",
    exercises: "1 / 3 bài tập",
    submissions: [
      { exercise: "Assignment 1: Terminal Setup", date: "26/05/2026", status: "Đã duyệt", statusClass: "badge-green" }
    ],
    certificates: [],
    notes: "Học viên phản hồi nội dung bài 2 hơi nhanh đối với người non-tech.",
    accountBalance: 500000,
    ledgerTransactions: []
  },
  {
    id: "4",
    name: "Mai Lan",
    email: "lan.mai@email.com",
    phone: "0765 432 109",
    status: "Active",
    statusClass: "badge-green",
    createdAt: "18/05/2026",
    updatedAt: "18/05/2026 11:20",
    avatar: "ML",
    avatarClass: "avatar-ml",
    needCourse: "Chưa xác định",
    needLevel: "Chưa biết lập trình",
    needGoal: "Tìm hiểu ngành để chuyển hướng",
    needNote: "Đăng ký tư vấn lộ trình.",
    courses: [],
    lessons: "0 bài học",
    quiz: "—",
    time: "—",
    exercises: "—",
    submissions: [],
    certificates: [],
    notes: "Chưa kích hoạt khóa học nào. Đang xếp lịch gọi tư vấn 1-1.",
    accountBalance: 0,
    ledgerTransactions: []
  },
  {
    id: "5",
    name: "Vũ Quang",
    email: "quangvu@email.com",
    phone: "0911 223 344",
    status: "Completed",
    statusClass: "badge-gray",
    createdAt: "12/05/2026",
    updatedAt: "05/06/2026 16:45",
    avatar: "VQ",
    avatarClass: "avatar-vq",
    needCourse: "AI Agent & Vibe Coding Bootcamp",
    needLevel: "Senior Developer",
    needGoal: "Lên chức Tech Lead",
    needNote: "Muốn học nâng cao về AI agents orchestration.",
    courses: [
      { name: "AI Agent & Vibe Coding Bootcamp", status: "Completed", statusClass: "badge-gray", progress: 100, progressClass: "green", date: "12/05/2026" }
    ],
    lessons: "24 / 24 bài học",
    quiz: "9.8 / 10",
    time: "36 giờ 00 phút",
    exercises: "6 / 6 bài tập",
    submissions: [
      { exercise: "Capstone Project: AI Orchestrator MVP", date: "02/06/2026", status: "Đã duyệt", statusClass: "badge-green" }
    ],
    certificates: [
      { name: "Chứng chỉ AI Agent Bootcamp", code: "CERT-AI-88192", date: "05/06/2026" }
    ],
    notes: "Project capstone đạt điểm tối đa. Rất xuất sắc.",
    accountBalance: 0,
    ledgerTransactions: []
  },
  {
    id: "6",
    name: "Hoàng Tú",
    email: "tu.hoang@email.com",
    phone: "0832 999 888",
    status: "Blocked",
    statusClass: "badge-red",
    createdAt: "10/05/2026",
    updatedAt: "20/05/2026 10:30",
    avatar: "HT",
    avatarClass: "avatar-ht",
    needCourse: "AI Agent & Vibe Coding Bootcamp",
    needLevel: "Junior Web Developer",
    needGoal: "Chuyển ngành sang AI Developer",
    needNote: "Tập trung vào phần thực hành dự án.",
    courses: [
      { name: "AI Agent & Vibe Coding Bootcamp", status: "Blocked", statusClass: "badge-red", progress: 0, progressClass: "gray", date: "10/05/2026" }
    ],
    lessons: "0 / 24 bài học",
    quiz: "—",
    time: "0 phút",
    exercises: "0 / 6 bài tập",
    submissions: [],
    certificates: [],
    notes: "Tài khoản bị khóa do hệ thống phát hiện đăng nhập đồng thời từ nhiều địa chỉ IP khác nhau.",
    accountBalance: 0,
    ledgerTransactions: []
  },
  {
    id: "7",
    name: "Quỳnh Như",
    email: "nhu.quynh@email.com",
    phone: "0345 678 912",
    status: "Active",
    statusClass: "badge-green",
    createdAt: "08/05/2026",
    updatedAt: "15/05/2026 11:22",
    avatar: "QN",
    avatarClass: "avatar-qn",
    needCourse: "Vibe Coding Basics",
    needLevel: "Product Manager",
    needGoal: "Tự làm MVP cho startup",
    needNote: "Tập trung vào phát triển nhanh MVP.",
    courses: [
      { name: "Vibe Coding Basics", status: "Active", statusClass: "badge-green", progress: 35, progressClass: "orange", date: "08/05/2026" }
    ],
    lessons: "3 / 10 bài học",
    quiz: "8.0 / 10",
    time: "6 giờ 30 phút",
    exercises: "1 / 3 bài tập",
    submissions: [
      { exercise: "Assignment 1: PM Workflow with Cursor", date: "12/05/2026", status: "Đã duyệt", statusClass: "badge-green" }
    ],
    certificates: [],
    notes: "Nắm bắt logic nhanh, chủ động trao đổi các mẫu prompt tối ưu.",
    accountBalance: 0,
    ledgerTransactions: []
  },
  {
    id: "8",
    name: "Đỗ Thành",
    email: "thanh.do@email.com",
    phone: "0966 555 444",
    status: "Active",
    statusClass: "badge-green",
    createdAt: "05/05/2026",
    updatedAt: "10/05/2026 14:15",
    avatar: "DT",
    avatarClass: "avatar-dt",
    needCourse: "AI Agent & Vibe Coding Bootcamp",
    needLevel: "Đã biết Javascript cơ bản",
    needGoal: "Trở thành Freelancer AI",
    needNote: "Muốn học thêm kỹ năng tìm khách hàng.",
    courses: [
      { name: "AI Agent & Vibe Coding Bootcamp", status: "Active", statusClass: "badge-green", progress: 60, progressClass: "green", date: "05/05/2026" },
      { name: "Vibe Coding Basics", status: "Completed", statusClass: "badge-gray", progress: 100, progressClass: "green", date: "15/04/2026" }
    ],
    lessons: "14 / 24 bài học",
    quiz: "8.7 / 10",
    time: "20 giờ 15 phút",
    exercises: "4 / 6 bài tập",
    submissions: [
      { exercise: "Assignment 3: Web App with Replit Agent", date: "08/05/2026", status: "Đã duyệt", statusClass: "badge-green" }
    ],
    certificates: [
      { name: "Chứng chỉ Vibe Coding Basics", code: "CERT-VIBE-55291", date: "15/04/2026" }
    ],
    notes: "Đang định hướng đi làm freelancer, cần hỗ trợ thêm phần đóng gói portfolio.",
    accountBalance: 250000,
    ledgerTransactions: []
  }
];

export const initialSubmissions: Submission[] = [
  {
    id: "submission-1",
    name: "Phạm Đức Trí",
    email: "tri.nguyen@example.com",
    avatarClass: "avatar-pt",
    course: "AI Agent & Vibe Coding Bootcamp",
    lesson: "Final Project – AI Landing Page",
    type: "Final Project",
    typeClass: "badge-indigo",
    status: "Chờ duyệt",
    statusClass: "badge-purple",
    date: "21/05/2026 14:32",
    projTitle: "AI Landing Page cho sản phẩm AI SaaS",
    projDesc: "Em xây landing page giới thiệu sản phẩm AI giúp tự động hóa công việc. Sử dụng Next.js, TailwindCSS và Framer Motion.",
    tech: "Next.js, TailwindCSS, TypeScript, Framer Motion, Vercel",
    learned: "Hiểu hơn về UI animation và tối ưu hiệu năng trang.",
    challenge: "Tối ưu animation trên mobile và xử lý SEO metadata.",
    demoUrl: "https://ai-landing-tri.vercel.app",
    sourceUrl: "https://github.com/trindev/ai-landing",
    fileName: "AI_Landing_Page_Demo.pdf",
    fileSize: "2.4 MB",
    attempt_no: 1,
    tools_used: "Claude 3.5 Sonnet, v0.dev",
    reflection: "Sử dụng v0 để dựng layout nhanh chóng, sau đó dùng Claude để tích hợp tương tác và viết hiệu ứng chuyển động mượt mà. Học được cách tối ưu CSS animation.",
  },
  {
    id: "submission-2",
    name: "Nguyễn Hoàng Anh",
    email: "hoanganh@gmail.com",
    avatarClass: "avatar-nh",
    course: "AI Agent & Vibe Coding Bootcamp",
    lesson: "Bài tập: Viết prompt tạo layout",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Chờ duyệt",
    statusClass: "badge-purple",
    date: "21/05/2026 09:15",
    projTitle: "Layout Vibe Coding Portfolio",
    projDesc: "Tối ưu hóa prompt để Claude Code dựng layout trang portfolio cá nhân siêu tốc.",
    tech: "Claude 3.5 Sonnet, HTML, Vanilla CSS",
    learned: "Biết cách chia nhỏ cấu trúc prompt và sử dụng block style.",
    challenge: "Đường truyền layout responsive đồng đều giữa các section.",
    demoUrl: "https://hoanganh-portfolio.vercel.app",
    sourceUrl: "https://github.com/hoanganh/vibe-portfolio",
    fileName: "Portfolio_Structure.zip",
    fileSize: "1.2 MB",
    attempt_no: 1,
    tools_used: "Claude Code, Cursor",
    reflection: "Thử nghiệm prompt lặp để cải thiện thiết kế responsive. AI tạo code nhanh nhưng đôi khi bị trùng thẻ hoặc CSS ad-hoc, cần tự tối ưu lại.",
  },
  {
    id: "submission-3",
    name: "Mai Lan",
    email: "mailan.le@example.com",
    avatarClass: "avatar-ml",
    course: "Web Development with Next.js",
    lesson: "Bài tập 2: Tạo landing đầu tiên",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Chờ duyệt",
    statusClass: "badge-purple",
    date: "20/05/2026 16:48",
    projTitle: "Landing Page Bán Cà Phê Sinh Thái",
    projDesc: "Trang landing giới thiệu và đặt mua cà phê organic, tối ưu LCP và SEO.",
    tech: "Next.js 14 (App Router), Vanilla CSS",
    learned: "Nắm chắc kiến thức Server Actions và Route Handlers.",
    challenge: "Tối ưu hóa ảnh chất lượng cao mà vẫn đạt điểm Lighthouse LCP tốt.",
    demoUrl: "https://ecocoffee.vercel.app",
    sourceUrl: "https://github.com/mailan/eco-coffee",
    fileName: "Eco_Coffee_Design.pdf",
    fileSize: "4.8 MB",
    attempt_no: 1,
    tools_used: "ChatGPT, v0.dev",
    reflection: "Tập trung viết CSS thuần thay vì Tailwind để rèn luyện kỹ năng Flexbox và Grid. Nhận xét: Web tải nhanh, đạt 98 điểm Lighthouse.",
  },
  {
    id: "submission-4",
    name: "Võ Thị Khánh",
    email: "khanh.vo@example.com",
    avatarClass: "avatar-vt",
    course: "AI Automation Fundamentals",
    lesson: "Bài tập 1: Automation workflow",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Yêu cầu chỉnh sửa",
    statusClass: "badge-orange",
    date: "20/05/2026 11:21",
    projTitle: "Hệ thống tự động hóa Marketing Lead qua n8n",
    projDesc: "Workflow đồng bộ dữ liệu từ Google Sheets sang HubSpot CRM và gửi email cảm ơn qua SendGrid.",
    tech: "n8n, Google Sheets API, HubSpot CRM, SendGrid",
    learned: "Hiểu cơ chế webhook và parsing JSON data.",
    challenge: "Xử lý lỗi duplicate data khi webhook gửi tin trùng lặp.",
    demoUrl: "https://n8n.cloud/workflow/marketing-leads",
    sourceUrl: "https://github.com/khanhvo/n8n-marketing-workflow",
    fileName: "marketing_workflow.json",
    fileSize: "45 KB",
    attempt_no: 2,
    tools_used: "ChatGPT-4o",
    reflection: "Đã sửa lại lỗi parse JSON ở Node 3 như giảng viên góp ý ở attempt 1, tuy nhiên vẫn cần tối ưu điều kiện lọc lead trùng.",
    reviewed_by: "Instructor Tuấn",
    reviewed_at: "20/05/2026 15:40"
  },
  {
    id: "submission-5",
    name: "Đỗ Quang Minh",
    email: "minhdo@outlook.com",
    avatarClass: "avatar-vq",
    course: "Mobile App Development",
    lesson: "Final Project – Todo App",
    type: "Final Project",
    typeClass: "badge-indigo",
    status: "Đã duyệt",
    statusClass: "badge-green",
    date: "19/05/2026 20:05",
    projTitle: "Todo List App tích hợp Widget và Cloud Sync",
    projDesc: "Ứng dụng quản lý công việc hàng ngày với giao diện Glassmorphism, đồng bộ Cloud Firestore.",
    tech: "Flutter, Firebase Firestore, Provider, Local Notifications",
    learned: "Quản lý state phức tạp và tối ưu local data caching.",
    challenge: "Đồng bộ offline data sang online mượt mà không bị xung đột timeline.",
    demoUrl: "https://play.google.com/store/apps/details?id=todo.minhdo",
    sourceUrl: "https://github.com/minhdo/todo-flutter",
    fileName: "Todo_Flutter_Build.apk",
    fileSize: "18.4 MB",
    attempt_no: 2,
    tools_used: "GitHub Copilot, ChatGPT",
    reflection: "Đã thêm tính năng đồng bộ background ở lần nộp này. Ứng dụng chạy mượt mà trên cả máy ảo Android và thiết bị iOS thật.",
    reviewed_by: "Instructor Tuấn",
    reviewed_at: "20/05/2026 10:12"
  },
  {
    id: "submission-6",
    name: "Hoàng Bảo",
    email: "baohoang@gmail.com",
    avatarClass: "avatar-ht",
    course: "AI Automation Fundamentals",
    lesson: "Bài tập: Workflow cơ bản",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Chờ duyệt",
    statusClass: "badge-purple",
    date: "19/05/2026 15:16",
    projTitle: "Workflow Tự Động Lưu File Email Vào Google Drive",
    projDesc: "Sử dụng n8n để lắng nghe email mới có đính kèm từ khách hàng, tự động tải xuống và lưu vào Drive theo tên khách hàng.",
    tech: "n8n, Gmail API, Google Drive API",
    learned: "Cách lấy token OAuth2 cho Google APIs và trích xuất file đính kèm.",
    challenge: "Định dạng lại tên file tiếng Việt có dấu tránh lỗi hiển thị.",
    demoUrl: "https://n8n.cloud/workflow/email-attachments",
    sourceUrl: "https://github.com/baohoang/n8n-drive-sync",
    fileName: "email_sync_drive.json",
    fileSize: "32 KB",
    attempt_no: 1,
    tools_used: "ChatGPT",
    reflection: "Tìm hiểu cách lấy và lọc tệp từ attachment của mail, viết script JS đơn giản để chuẩn hóa tên tệp.",
  },
  {
    id: "submission-7",
    name: "Ngọc Trâm",
    email: "tramngoc@live.com",
    avatarClass: "avatar-qn",
    course: "Mobile App Development",
    lesson: "Bài tập: State Management",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Yêu cầu chỉnh sửa",
    statusClass: "badge-orange",
    date: "19/05/2026 10:42",
    projTitle: "Shopping Cart State Management với Riverpod",
    projDesc: "Bài tập thực hành quản lý giỏ hàng trực tuyến bằng Flutter Riverpod, cập nhật số lượng, tổng tiền realtime.",
    tech: "Flutter, Riverpod, Dart",
    learned: "Nắm vững StateNotifier và ChangeNotifier Provider.",
    challenge: "UI không tự động re-render khi cập nhật thuộc tính nhỏ trong class sản phẩm.",
    demoUrl: "https://tram-shopping-cart.web.app",
    sourceUrl: "https://github.com/tramngoc/riverpod-cart",
    fileName: "cart_riverpod_project.zip",
    fileSize: "2.1 MB",
    attempt_no: 1,
    tools_used: "ChatGPT, Phind",
    reflection: "Quá trình lưu trữ state của Riverpod phức tạp hơn Provider, em cần thời gian làm quen với Immutable State.",
    reviewed_by: "Instructor Tuấn",
    reviewed_at: "19/05/2026 16:30"
  },
  {
    id: "submission-8",
    name: "Khánh Duy",
    email: "duykhanh@gmail.com",
    avatarClass: "avatar-dt",
    course: "AI Agent & Vibe Coding Bootcamp",
    lesson: "Bài tập 1: AI và tương tác người dùng",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Từ chối",
    statusClass: "badge-red",
    date: "18/05/2026 18:30",
    projTitle: "Chatbot Tự Động Trả Lời FAQs",
    projDesc: "Sao chép đoạn mã nguồn chatbot của người khác và sửa đổi sơ sài tiêu đề.",
    tech: "HTML, CSS, JS",
    learned: "Không có nhiều bài học.",
    challenge: "Không gặp thách thức nào đáng kể.",
    demoUrl: "https://faqs-chatbot-copy.vercel.app",
    sourceUrl: "https://github.com/duykhanh/faq-chatbot-copy",
    fileName: "faq_chatbot.zip",
    fileSize: "300 KB",
    attempt_no: 1,
    tools_used: "None",
    reflection: "Em nộp bài này để lấy lượt xem đáp án, em chưa có thời gian tự code.",
    reviewed_by: "Instructor Tuấn",
    reviewed_at: "18/05/2026 19:15"
  },
  {
    id: "submission-9",
    name: "Yến Linh",
    email: "yenlinh@gmail.com",
    avatarClass: "avatar-ml",
    course: "Web Development with Next.js",
    lesson: "Bài tập: Component & Props",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Đã duyệt",
    statusClass: "badge-green",
    date: "18/05/2026 16:40",
    projTitle: "Dashboard Component Card Library",
    projDesc: "Tạo bộ library các component card nhỏ dùng cho trang dashboard bán hàng, sử dụng props linh hoạt để tùy biến màu sắc, icon.",
    tech: "Next.js, React, TailwindCSS",
    learned: "Hiểu sâu về Reusability và Children Props trong React.",
    challenge: "Xử lý typescript type cho icon props linh hoạt.",
    demoUrl: "https://dash-cards-yenlinh.vercel.app",
    sourceUrl: "https://github.com/yenlinh/nextjs-component-cards",
    fileName: "Dashboard_Cards_Lib.zip",
    fileSize: "1.5 MB",
    attempt_no: 1,
    tools_used: "Claude Code, v0.dev",
    reflection: "Tận dụng tốt tính chất props để giảm bớt code dư thừa. Bộ component rất linh hoạt và dễ tái sử dụng.",
    reviewed_by: "Instructor Tuấn",
    reviewed_at: "18/05/2026 18:20"
  },
  {
    id: "submission-10",
    name: "Quang Nam",
    email: "quangnam@gmail.com",
    avatarClass: "avatar-qn",
    course: "AI Automation Fundamentals",
    lesson: "Bài tập: API Integration",
    type: "Assignment",
    typeClass: "badge-orange",
    status: "Chờ duyệt",
    statusClass: "badge-purple",
    date: "18/05/2026 10:22",
    projTitle: "Tích Hợp API Thời Tiết Gửi SMS Hàng Ngày",
    projDesc: "Workflow n8n tích hợp OpenWeatherMap API to lấy thông tin thời tiết lúc 7h sáng, sau đó dùng Twilio gửi tin nhắn SMS tóm tắt tới điện thoại cá nhân.",
    tech: "n8n, Weather API, Twilio API",
    learned: "Cách cấu hình HTTP Request Node và xử lý dữ liệu JSON nested.",
    challenge: "Đăng ký tài khoản thử nghiệm Twilio bị chặn số điện thoại Việt Nam.",
    demoUrl: "https://n8n.cloud/workflow/weather-sms",
    sourceUrl: "https://github.com/quangnam/n8n-weather-twilio",
    fileName: "weather_sms_workflow.json",
    fileSize: "18 KB",
    attempt_no: 1,
    tools_used: "ChatGPT-4o",
    reflection: "Đã hoàn tất tích hợp thành công, tin nhắn SMS gửi về chính xác hàng ngày.",
  }
];

export const initialInvoices: Invoice[] = [
  {
    id: "INV-2026-001085",
    orderCode: "MAY-ORD-2026-0001",
    studentName: "Phạm Đức Trí",
    studentEmail: "tri@email.com",
    studentPhone: "0987 654 321",
    studentAddress: "123 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh",
    course: "AI Agent & Vibe Coding Bootcamp",
    courseCode: "ai",
    issuedDate: "21/05/2026 14:35",
    totalRaw: "2.990.000đ",
    discount: "-300.000đ",
    amount: "2.690.000đ",
    status: "issued",
    statusName: "Đã phát hành"
  },
  {
    id: "INV-2026-001081",
    orderCode: "MAY-ORD-2026-0005",
    studentName: "Đỗ Hoàng Anh",
    studentEmail: "anhdo@gmail.com",
    studentPhone: "0912 345 678",
    studentAddress: "456 Trần Hưng Đạo, Quận 5, TP. Hồ Chí Minh",
    course: "Python for Data Analysis",
    courseCode: "python",
    issuedDate: "18/05/2026 16:40",
    totalRaw: "990.000đ",
    discount: "0đ",
    amount: "990.000đ",
    status: "canceled",
    statusName: "Đã hủy"
  },
  {
    id: "INV-2026-001080",
    orderCode: "MAY-ORD-2026-0008",
    studentName: "Nguyễn Thu Hà",
    studentEmail: "ha.nguyen@gmail.com",
    studentPhone: "0934 567 890",
    studentAddress: "789 Lê Lợi, Quận Hải Châu, Đà Nẵng",
    course: "AI Agent & Vibe Coding Bootcamp",
    courseCode: "ai",
    issuedDate: "16/05/2026 18:30",
    totalRaw: "2.990.000đ",
    discount: "-300.000đ",
    amount: "2.690.000đ",
    status: "issued",
    statusName: "Đã phát hành"
  },
  {
    id: "INV-2026-001078",
    orderCode: "MAY-ORD-2026-0002",
    studentName: "Trần Thị Bình",
    studentEmail: "binh.tran@email.com",
    studentPhone: "0909 123 456",
    studentAddress: "12 Lý Tự Trọng, Quận Hoàn Kiếm, Hà Nội",
    course: "Starter Mini Course",
    courseCode: "starter",
    issuedDate: "14/05/2026 10:45",
    totalRaw: "590.000đ",
    discount: "0đ",
    amount: "590.000đ",
    status: "issued",
    statusName: "Đã phát hành"
  }
];

export const initialCoupons: Coupon[] = [
  {
    code: "WELCOME10",
    name: "Welcome 10%",
    type: "percentage",
    typeName: "Percentage",
    value: "10%",
    scope: "All Courses",
    duration: "01/05/2026 - 31/05/2026",
    redemptions: "128 / 300",
    redemptionsUsed: 128,
    redemptionsMax: 300,
    status: "active",
    desc: "Mã giảm giá áp dụng cho học viên đăng ký mới nhận ưu đãi 10%.",
    maxDiscount: 300000,
    minSpend: 0,
    limitUser: 1,
    stack: false
  },
  {
    code: "VIP100K",
    name: "Giảm 100K cho Core",
    type: "fixed",
    typeName: "Fixed Amount",
    value: "100.000đ",
    scope: "Core Level",
    duration: "01/05/2026 - 30/06/2026",
    redemptions: "32 / 200",
    redemptionsUsed: 32,
    redemptionsMax: 200,
    status: "active",
    desc: "Mã giảm giá trực tiếp 100k cho các khóa học thuộc Level Core.",
    maxDiscount: 100000,
    minSpend: 1000000,
    limitUser: 1,
    stack: false
  },
  {
    code: "ADVANCE15",
    name: "Advanced 15%",
    type: "percentage",
    typeName: "Percentage",
    value: "15%",
    scope: "Advanced Level",
    duration: "01/03/2026 - 31/05/2026",
    redemptions: "88 / 150",
    redemptionsUsed: 88,
    redemptionsMax: 150,
    status: "paused",
    desc: "Ưu đãi 15% cho người tự học nâng cấp level.",
    maxDiscount: 500000,
    minSpend: 4000000,
    limitUser: 1,
    stack: true
  },
  {
    code: "SUMMER30",
    name: "Summer Sale 30%",
    type: "percentage",
    typeName: "Percentage",
    value: "30%",
    scope: "All Courses",
    duration: "01/04/2026 - 01/05/2026",
    redemptions: "420 / 500",
    redemptionsUsed: 420,
    redemptionsMax: 500,
    status: "expired",
    desc: "Đợt xả kho hè ưu đãi kịch sàn lên đến 30% cho mọi người.",
    maxDiscount: 1000000,
    minSpend: 0,
    limitUser: 1,
    stack: false
  },
  {
    code: "STUDENT30",
    name: "Student Discount 30%",
    type: "percentage",
    typeName: "Percentage",
    value: "30%",
    scope: "Starter Level",
    duration: "01/02/2026 - 28/02/2026",
    redemptions: "75 / 100",
    redemptionsUsed: 75,
    redemptionsMax: 100,
    status: "archived",
    desc: "Mã giảm học sinh sinh viên cần tất toán thẻ.",
    maxDiscount: 200000,
    minSpend: 500000,
    limitUser: 1,
    stack: false
  }
];

export const initialLeads: Lead[] = [
  {
    id: "lead_1",
    name: "Nguyễn Minh Anh",
    initials: "MA",
    avatarClass: "avatar-nv",
    email: "minhanh@gmail.com",
    phone: "0988 123 456",
    needs: "AI Agent & Vibe Coding Bootcamp",
    source: "contact_page",
    sourceType: "globe",
    status: "new",
    statusName: "NEW",
    createdAt: "21/05/2026 14:32",
    request: "Mình muốn tìm hiểu khóa học AI Agent cho người mới bắt đầu. Cho mình xin thông tin chi tiết và lịch khai giảng gần nhất.",
    note: "Đã gọi điện tư vấn lần 1, quan tâm khóa AI Agent cơ bản. Sẽ gửi chương trình học qua email.",
    noteUpdated: "Cập nhật: 21/05/2026 15:20 bởi Admin User"
  },
  {
    id: "lead_2",
    name: "Trần Quang Huy",
    initials: "QH",
    avatarClass: "avatar-tt",
    email: "huytq@gmail.com",
    phone: "0912 345 678",
    needs: "Vibe Coding Basics",
    source: "workshop_signup",
    sourceType: "users",
    status: "contacted",
    statusName: "CONTACTED",
    createdAt: "21/05/2026 09:15",
    request: "Đăng ký tham gia workshop 'AI Agent Vibe Coding' ngày 25/05/2026.",
    note: "Học viên có nền tảng lập trình tốt. Sẽ tư vấn khóa Bootcamp sau buổi workshop kết thúc.",
    noteUpdated: "Cập nhật: 21/05/2026 09:20 bởi Admin User"
  },
  {
    id: "lead_3",
    name: "Hoàng Yến Nhi",
    initials: "YN",
    avatarClass: "avatar-lm",
    email: "yenhi@gmail.com",
    phone: "0966 555 888",
    needs: "AI Agent & Vibe Coding Bootcamp",
    source: "contact_page",
    sourceType: "globe",
    status: "lost",
    statusName: "LOST",
    createdAt: "20/05/2026 10:02",
    request: "Xin báo giá khóa học cho doanh nghiệp 10 người.",
    note: "Gọi điện 3 lần không liên lạc được, email không phản hồi. Đánh dấu tạm ngưng chăm sóc.",
    noteUpdated: "Cập nhật: 20/05/2026 17:40 bởi Admin User"
  }
];

export const initialAnnouncements: Announcement[] = [
  {
    id: "ANN-2026-0001",
    title: "Thông báo bảo trì hệ thống",
    desc: "Hệ thống sẽ bảo trì định kỳ vào Chủ nhật, ngày 08/06/2026 từ 02:00 - 04:00 (GMT+7). Trong thời gian này, nền tảng có thể gián đoạn truy cập. Rất mong bạn thông cảm. Cảm ơn bạn đã đồng hành cùng Blueprint!",
    scope: "global",
    scopeName: "Global",
    course: "—",
    courseCode: "",
    priority: "high",
    priorityName: "Cao",
    status: "published",
    statusName: "Đã xuất bản",
    publishedAt: "01/06/2026 10:30",
    author: "Admin User",
    recipients: "1,248",
    success: "1,245 (99.8%)",
    failed: "3 (0.2%)"
  },
  {
    id: "ANN-2026-0002",
    title: "Lịch học buổi live tuần này",
    desc: "Lịch học trực tuyến (Live Session) tuần này sẽ diễn ra vào lúc 20:00 ngày Thứ 5 (11/06/2026). Chủ đề: Giải đáp thắc mắc và Review code Final Project.",
    scope: "course",
    scopeName: "Course",
    course: "AI Agent & Vibe Coding Bootcamp",
    courseCode: "ai",
    priority: "medium",
    priorityName: "Trung bình",
    status: "published",
    statusName: "Đã xuất bản",
    publishedAt: "31/05/2026 19:00",
    author: "Instructor",
    recipients: "38",
    success: "38 (100%)",
    failed: "0 (0%)"
  },
  {
    id: "ANN-2026-0003",
    title: "Ưu đãi 20% cho học viên cũ",
    desc: "Chiến dịch tri ân học viên cũ: Giảm giá 20% khi đăng ký khóa học tiếp theo trong hệ thống. Thời hạn áp dụng từ nay đến hết 30/06/2026.",
    scope: "global",
    scopeName: "Global",
    course: "—",
    courseCode: "",
    priority: "low",
    priorityName: "Thấp",
    status: "draft",
    statusName: "Bản nháp",
    publishedAt: "—",
    author: "Admin User",
    recipients: "0",
    success: "—",
    failed: "—"
  },
  {
    id: "ANN-2026-0004",
    title: "Thông báo lớp học đặc biệt",
    desc: "Gửi thông tin tài liệu lớp học chuyên đề AI Automation đặc biệt cho học viên VIP.",
    scope: "course",
    scopeName: "Course",
    course: "AI Agent & Vibe Coding Bootcamp",
    courseCode: "ai",
    priority: "high",
    priorityName: "Cao",
    status: "failed",
    statusName: "Giao thất bại",
    publishedAt: "18/04/2026 09:20",
    author: "Instructor",
    recipients: "12",
    success: "9 (75%)",
    failed: "3 (25%)"
  },
  {
    id: "ANN-2026-0005",
    title: "Cập nhật bài tập khóa n8n",
    desc: "Đã có bài tập mới cho module 3 khóa học Web Automation n8n.",
    scope: "course",
    scopeName: "Course",
    course: "Web Automation with n8n",
    courseCode: "n8n",
    priority: "medium",
    priorityName: "Trung bình",
    status: "published",
    statusName: "Đã xuất bản",
    publishedAt: "28/05/2026 14:00",
    author: "Admin User",
    recipients: "20",
    success: "20 (100%)",
    failed: "0 (0%)"
  }
];

export const initialReviews: Review[] = [
  {
    id: "REV-2026-0001",
    name: "Võ Thị Khánh",
    email: "khanh.vo@email.com",
    avatarClass: "avatar-vt",
    avatarText: "VT",
    course: "AI Agent & Vibe Coding Bootcamp",
    courseCode: "ai",
    rating: 5,
    comment: "Khóa học rất thực tế. Giảng viên giải thích cặn kẽ và các bài thực hành giúp tôi tự xây dựng được Agent chạy tự động.",
    status: "pending",
    statusName: "Chờ duyệt",
    date: "05/06/2026 14:22",
    reply: "",
    moderationLogs: []
  },
  {
    id: "REV-2026-0002",
    name: "Nguyễn Văn An",
    email: "an.nguyen@email.com",
    avatarClass: "avatar-nv",
    avatarText: "NV",
    course: "AI Agent & Vibe Coding Bootcamp",
    courseCode: "ai",
    rating: 5,
    comment: "Tuyệt vời! Nội dung học cập nhật những tool mới nhất như Cursor AI, v0 dev. Rất đáng tiền.",
    status: "approved",
    statusName: "Đã duyệt",
    date: "04/06/2026 09:15",
    reply: "Cảm ơn bạn đã phản hồi! Chúc bạn ứng dụng tốt các tool AI vào công việc.",
    moderationLogs: [
      { action: "Phê duyệt", actor: "Admin User", time: "04/06/2026 10:00", note: "Approved public review" }
    ]
  },
  {
    id: "REV-2026-0003",
    name: "Trần Thị Bình",
    email: "binh.tran@email.com",
    avatarClass: "avatar-tt",
    avatarText: "TT",
    course: "Web Automation with n8n",
    courseCode: "n8n",
    rating: 4,
    comment: "Bài thực hành hơi nhanh một chút đối với người mới. Nhưng workflow mẫu rất chất lượng.",
    status: "approved",
    statusName: "Đã duyệt",
    date: "02/06/2026 18:40",
    reply: "",
    moderationLogs: []
  },
  {
    id: "REV-2026-0004",
    name: "Lê Minh Châu",
    email: "chau.le@email.com",
    avatarClass: "avatar-lm",
    avatarText: "LM",
    course: "Web Automation with n8n",
    courseCode: "n8n",
    rating: 2,
    comment: "Hệ thống nộp bài lỗi liên tục, không chấm được điểm.",
    status: "hidden",
    statusName: "Đã ẩn",
    date: "28/05/2026 11:10",
    reply: "Chào Châu, ban kỹ thuật đã liên hệ hỗ trợ riêng để kiểm tra tài khoản nộp bài của bạn rồi nhé.",
    moderationLogs: [
      { action: "Ẩn review", actor: "Admin User", time: "28/05/2026 14:00", note: "Spam / system issue discussion handled privately" }
    ]
  }
];

export const initialPayments: PaymentTransaction[] = [
  {
    orderCode: "MAY-ORD-2026-0001",
    provider: "vnpay",
    providerName: "VNPay",
    txId: "241234124124123",
    eventId: "VNPAY_20260521_00123",
    amount: "2.690.000đ",
    currency: "VND",
    status: "success",
    statusText: "Thanh toán thành công",
    createdAt: "21/05/2026 14:32",
    course: "AI Agent & Vibe Coding Bootcamp",
    idempotency: "ord_may-ord-2026-0001_vnpay",
    rawJson: '{\n  "provider": "vnpay",\n  "transaction_id": "241234124124123",\n  "amount": 2690000,\n  "status": "success",\n  "event_id": "VNPAY_20260521_00123",\n  "verified_at": "2026-05-21T14:32:00Z"\n}'
  },
  {
    orderCode: "MAY-ORD-2026-0003",
    provider: "vnpay",
    providerName: "VNPay",
    txId: "2412341241234124",
    eventId: "VNPAY_20260521_00234",
    amount: "1.990.000đ",
    currency: "VND",
    status: "pending",
    statusText: "Đang chờ thanh toán",
    createdAt: "21/05/2026 09:45",
    course: "Starter Mini Course",
    idempotency: "ord_may-ord-2026-0003_vnpay",
    rawJson: '{\n  "provider": "vnpay",\n  "transaction_id": "2412341241234124",\n  "amount": 1990000,\n  "status": "pending",\n  "event_id": "VNPAY_20260521_00234"\n}'
  },
  {
    orderCode: "MAY-ORD-2026-0005",
    provider: "momo",
    providerName: "MoMo",
    txId: "51048289028",
    eventId: "MOMO_20260518_00321",
    amount: "990.000đ",
    currency: "VND",
    status: "failed",
    statusText: "Giao dịch thất bại (Hủy)",
    createdAt: "18/05/2026 16:30",
    course: "Python for Data Analysis",
    idempotency: "ord_may-ord-2026-0005_momo",
    rawJson: '{\n  "provider": "momo",\n  "transaction_id": "51048289028",\n  "amount": 990000,\n  "status": "failed",\n  "error_code": 49,\n  "message": "User canceled transaction"\n}'
  },
  {
    orderCode: "MAY-ORD-2026-0007",
    provider: "bank",
    providerName: "Bank Transfer",
    txId: "FT2605170092",
    eventId: "BANK_20260517_00098",
    amount: "5.990.000đ",
    currency: "VND",
    status: "success",
    statusText: "Chuyển khoản thành công",
    createdAt: "17/05/2026 10:15",
    course: "Advanced Automation",
    idempotency: "ord_may-ord-2026-0007_bank",
    rawJson: '{\n  "provider": "bank",\n  "transaction_id": "FT2605170092",\n  "amount": 5990000,\n  "status": "success",\n  "bank_code": "VCB"\n}'
  },
  {
    orderCode: "MAY-ORD-2026-0008",
    provider: "vnpay",
    providerName: "VNPay",
    txId: "2412341241234129",
    eventId: "VNPAY_20260516_00456",
    amount: "2.690.000đ",
    currency: "VND",
    status: "success",
    statusText: "Thanh toán thành công",
    createdAt: "16/05/2026 18:22",
    course: "AI Agent & Vibe Coding Bootcamp",
    idempotency: "ord_may-ord-2026-0008_vnpay",
    rawJson: '{\n  "provider": "vnpay",\n  "transaction_id": "2412341241234129",\n  "amount": 2690000,\n  "status": "success"\n}'
  },
  {
    orderCode: "MAY-ORD-2026-0010",
    provider: "momo",
    providerName: "MoMo",
    txId: "51048289110",
    eventId: "MOMO_20260515_00998",
    amount: "12.000.000đ",
    currency: "VND",
    status: "pending",
    statusText: "Chờ xác nhận giao dịch",
    createdAt: "15/05/2026 21:05",
    course: "Premium Mentoring",
    idempotency: "ord_may-ord-2026-0010_momo",
    rawJson: '{\n  "provider": "momo",\n  "transaction_id": "51048289110",\n  "amount": 12000000,\n  "status": "pending"\n}'
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "LOG-2026-0001",
    time: "07/06/2026 10:45:12",
    actor: "Admin User",
    email: "admin@blueprint.edu",
    action: "COURSE_UPDATE",
    category: "course",
    ip: "113.23.45.167",
    desc: "Cập nhật nội dung bài học số 4 khóa AI Agent & Vibe Coding Bootcamp.",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    meta: {
      course_id: "course_ai_agent_bootcamp",
      lesson_id: "lesson_4",
      fields_changed: ["title", "short_desc"],
      old_values: { title: "Chấm điểm bài học", short_desc: "Hướng dẫn" },
      new_values: { title: "Tự động chấm điểm", short_desc: "Tự động hóa với LLM" }
    }
  },
  {
    id: "LOG-2026-0002",
    time: "06/06/2026 15:30:45",
    actor: "Admin User",
    email: "admin@blueprint.edu",
    action: "STUDENT_BAN",
    category: "student",
    ip: "113.23.45.167",
    desc: "Tạm khóa tài khoản học viên khanh.vo@email.com do vi phạm điều khoản sao chép mã nguồn.",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    meta: {
      student_id: "user_vt_0012",
      action: "ban",
      reason: "Source code plagiarism detected on submission #12",
      expiry_date: "2026-07-06T15:30:00Z"
    }
  },
  {
    id: "LOG-2026-0003",
    time: "05/06/2026 09:12:01",
    actor: "Lê Văn Tám",
    email: "tam.le@blueprint.edu",
    action: "PAYMENT_APPROVE",
    category: "payment",
    ip: "27.72.100.85",
    desc: "Phê duyệt giao dịch thanh toán thủ công cho đơn hàng MAY-ORD-2026-0038.",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    meta: {
      order_code: "MAY-ORD-2026-0038",
      payment_provider: "manual_bank_transfer",
      amount: 2400000,
      approved_by: "tam.le@blueprint.edu"
    }
  },
  {
    id: "LOG-2026-0004",
    time: "03/06/2026 16:40:22",
    actor: "Admin User",
    email: "admin@blueprint.edu",
    action: "SETTINGS_CHANGE",
    category: "settings",
    ip: "113.23.45.167",
    desc: "Thay đổi thông tin cấu hình cổng tích hợp Momo API key.",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    meta: {
      integration: "momo_qr",
      changed_fields: ["api_endpoint", "partner_code"],
      api_endpoint_old: "https://test-payment.momo.vn",
      api_endpoint_new: "https://payment.momo.vn"
    }
  },
  {
    id: "LOG-2026-0005",
    time: "02/06/2026 23:55:10",
    actor: "Hệ thống bảo mật",
    email: "security-daemon@blueprint.sh",
    action: "SECURITY_ALERT",
    category: "security",
    ip: "185.220.101.4",
    desc: "Phát hiện số lượng lớn yêu cầu sai Token xác thực (Brute-force attempt) trên API endpoint /checkout/confirm.",
    userAgent: "python-requests/2.31.0",
    meta: {
      request_endpoint: "/api/v1/checkout/confirm",
      failures_count: 125,
      action_taken: "ip_temporary_blocked",
      blocked_duration_seconds: 3600
    }
  }
];

export const initialReferralCodes: ReferralCode[] = [
  {
    id: "1",
    owner: "Nguyễn Văn An",
    email: "an.nguyen@email.com",
    avatarText: "NA",
    code: "AN10",
    rate: "10%",
    conversions: 8,
    revenue: "28.000.000đ",
    commission: "2.800.000đ",
    status: "active",
    statusName: "Đang chạy"
  },
  {
    id: "2",
    owner: "Trần Thị Bình",
    email: "binh.tran@email.com",
    avatarText: "TB",
    code: "BINH15",
    rate: "15%",
    conversions: 14,
    revenue: "56.000.000đ",
    commission: "8.400.000đ",
    status: "active",
    statusName: "Đang chạy"
  },
  {
    id: "3",
    owner: "Lê Minh Châu",
    email: "chau.le@email.com",
    avatarText: "LC",
    code: "CHAU20",
    rate: "20%",
    conversions: 3,
    revenue: "9.000.000đ",
    commission: "1.800.000đ",
    status: "paused",
    statusName: "Tạm dừng"
  }
];

export const initialReferralConversions: ReferralConversion[] = [
  {
    id: "101",
    referrerName: "Nguyễn Văn An",
    referrerEmail: "an.nguyen@email.com",
    referrerCode: "AN10",
    referrerBank: "Techcombank - 1903829182901 - NGUYEN VAN AN",
    referredName: "Phạm Hải Nam",
    referredEmail: "nam.pham@email.com",
    referredCourse: "AI Agent & Vibe Coding Bootcamp",
    orderCode: "ORD-992019",
    orderAmount: "3,500,000đ",
    rewardAmount: "350,000đ",
    date: "06/06/2026 11:20",
    status: "pending",
    statusName: "Chờ duyệt"
  },
  {
    id: "102",
    referrerName: "Trần Thị Bình",
    referrerEmail: "binh.tran@email.com",
    referrerCode: "BINH15",
    referrerBank: "Vietcombank - 001100298192 - TRAN THI BINH",
    referredName: "Hoàng Minh Đức",
    referredEmail: "duc.hoang@email.com",
    referredCourse: "Web Automation n8n nâng cao",
    orderCode: "ORD-991082",
    orderAmount: "2,000,000đ",
    rewardAmount: "300,000đ",
    date: "05/06/2026 15:45",
    status: "approved",
    statusName: "Đã duyệt & chi"
  },
  {
    id: "103",
    referrerName: "Lê Minh Châu",
    referrerEmail: "chau.le@email.com",
    referrerCode: "CHAU20",
    referrerBank: "MB Bank - 09819281928 - LE MINH CHAU",
    referredName: "Đỗ Bảo Trâm",
    referredEmail: "tram.do@email.com",
    referredCourse: "AI Agent & Vibe Coding Bootcamp",
    orderCode: "ORD-990022",
    orderAmount: "3,500,000đ",
    rewardAmount: "700,000đ",
    date: "02/06/2026 09:15",
    status: "cancelled",
    statusName: "Bị hủy (Refund)"
  }
];
